name: deploy

on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize]

env:
  GH_USERNAME: "tlienart"
  REPO_PREFIX: "xranklin-build-tester"
  PREVIEWS_PREFIX: "previews/PR"  # followed by PR number
  BUILD_ACTION_REF: "tlienart/xranklin-build-action@dev"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: SET PREVIEW PATH IF PULL REQUEST
        run: |
          if ${{ github.event_name == 'pull_request' }}
          then
            echo 'PRID=${{ env.PREVIEWS_PREFIX}}${{ github.event.number}}' >> $GITHUB_ENV
          else
            echo 'PRID=' >> $GITHUB_ENV
          fi
        shell: bash

      - name: BUILD AND DEPLOY
        uses: ${{env.BUILD_ACTION_REF}}
        with:
          BASE_URL_PREFIX: ${{ env.REPO_PREFIX }}
          PREVIEW: ${{ env.PRID }}
          UPLOAD_ARTIFACTS: true

      - name: URL INDICATION
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview should be up in a couple of mins at https://${{ env.GH_USERNAME }}.github.io/${{ env.REPO_PREFIX }}/${{ env.PRID }} (if you get a 404, wait 30s then refresh).
        if: github.event_name == 'pull_request'