# NOTES:
#   - if your default branch is `master`, replace `main` by `master` in the "on" part.
#   - the `REPO_PREFIX` is the name of the repo; if the repo is USERNAME.github.io then leave empty.
#   - the `PREVIEWS_PREFIX` will be followed by the PR number so e.g. PR123 will go to `/previews/PR123/`
#   - this uses `@dev` version of the build action (see build and deploy step).
#       Users should use a tagged version or at least `@main` to avoid issues.
#

name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  GH_USERNAME: "tlienart"
  REPO_PREFIX: "xranklin-build-tester"
  PREVIEWS_PREFIX: "previews/PR"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: 👀 Set preview path for PRs
        run: |
          echo 'PRID=${{ env.PREVIEWS_PREFIX}}${{ github.event.number}}' >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
        shell: bash

      - name: 🚀 Build and Deploy
        uses: tlienart/xranklin-build-action@dev
        with:
          BASE_URL_PREFIX: ${{ env.REPO_PREFIX }}
          PREVIEW: ${{ env.PRID }}

      - name: 🗒️ Preview URL indication for PRs
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview should be up in a couple of mins at https://${{ env.GH_USERNAME }}.github.io/${{ env.REPO_PREFIX }}/${{ env.PRID }} (if you get a 404, wait 30s then refresh).
        if: github.event_name == 'pull_request'
